spring.application.name=backend

# ── Server ────────────────────────────────────────────────
server.port=8080

# ── MySQL Datasource ──────────────────────────────────────
spring.datasource.url=jdbc:mysql://localhost:3306/stockdb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ── JPA / Hibernate ───────────────────────────────────────
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# ── Swagger / OpenAPI ─────────────────────────────────────
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true

# JWT
# générer sur : https://generate-secret.vercel.app/64
jwt.secret=6b07788087025a06a6e98379c094d74f6fb6b86a43ef519c9bbfe4691b3057dd
jwt.access-token-expiration=900000
jwt.refresh-token-expiration=604800000
